version: '3'
services:
  phpapache:
    container_name: timetracker-phpapache
    build:
      context: .
      dockerfile: PHP-Apache.Dockerfile
    depends_on:
      - db
    volumes:
      - ../src/:/var/www/html/
    ports:
      - 8080:80
    restart: always

  db:
    container_name: timetracker-mysql
    image: mysql:latest
    ports:
        - 9906:3306
    volumes:
      - ../db/:/var/lib/mysql/
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: time_tracker
        MYSQL_USER: time-tracker-admin
        MYSQL_PASSWORD: D)2M*pDyuV0IAKqI
  
  phpmyadmin:
    container_name: timetracker-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
        - db
    ports:
        - 9907:80
    restart: always
    environment:
        PMA_HOST: db